export default {
  Username: 'Username',
  Password: 'Password',
  loggedIn: 'loggedIn',
  Name: 'Name',
  Email: 'Email',
  Lastname: 'Lastname',
  UserId: 'UserId',
  Url: 'url',
  textvalue: 'text',
  button_text: 'btn',
  msg: 'msg',
  pass: 'pass',
  Wrong: 'wrong',
  Token: 'Token',
  Android_Version: '0',
  ios_Version: '0',
  notificationID: '',

  rememberUserName: 'RememberUser',
  rememberuserpass: 'RememberPass',
};
