# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'StainManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StainManagement

  target 'StainManagement-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StainManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'StainManagement-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StainManagement-tvO

end
